# Use root/example as user/password credentials
version: '3.1'

services:

  user-service:
   image: user-service
   ports:
     - "8000-8000"
   networks:
     - user-service-mongo
   depends_on:
     - mongo


  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - user-service-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - user-service-mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/

networks:
  user-service-mongo:
    driver: bridge